## Python como Lenguaje del Mundo Lineal

### Fundamentos Computacionales del Álgebra Lineal


## Resumen

El álgebra lineal constituye el lenguaje matemático fundamental para describir sistemas donde la superposición y la proporcionalidad tienen sentido. En la era computacional, este lenguaje no se implementa como una colección de fórmulas aisladas, sino como una **infraestructura operativa** que permite representar, transformar y analizar información de alta dimensión.
Este documento establece el marco conceptual y técnico necesario para trabajar álgebra lineal de forma computacional utilizando Python, con énfasis en la correcta interpretación de vectores, matrices y tensores como **objetos matemáticos nativos**, y en la distinción rigurosa entre las distintas operaciones que pueden aplicarse sobre ellos.


## 1. La computación como extensión natural del álgebra lineal

En su forma abstracta, el álgebra lineal estudia estructuras definidas sobre espacios vectoriales. En computación científica, estas estructuras se materializan como **arreglos multidimensionales**, donde cada operación implementa una transformación algebraica precisa.

Python, a través del ecosistema científico (NumPy), no aproxima el álgebra lineal:
la **implementa directamente**.

La consecuencia inmediata es que:

* cada error conceptual se traduce en un error numérico,
* cada confusión algebraica produce un resultado incorrecto aunque el código “funcione”.

Por esta razón, el dominio computacional del álgebra lineal exige una comprensión estricta de:

* qué representa cada objeto,
* qué operación se está aplicando,
* y qué significado matemático tiene el resultado.

## 2. Vectores, matrices y tensores como objetos nativos

### 2.1 Vectores

Un vector es un elemento de un espacio vectorial. En computación, se representa como un arreglo unidimensional.


In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.3 MB 6.7 MB/s eta 0:00:02
   --------------------------- ------------ 8.4/12.3 MB 17.5 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 20.9 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

v = np.array([1, 2, 3])
u = np.array([4, 5, 6])

v, u

(array([1, 2, 3]), array([4, 5, 6]))

Interpretación matemática:

* `v ∈ ℝ³`
* `u ∈ ℝ³`

Estos objetos admiten:

* suma vectorial,
* multiplicación por escalar,
* producto interno (cuando está definido).

### 2.2 Matrices

Una matriz representa:

1. una colección ordenada de vectores, o
2. una transformación lineal entre espacios vectoriales.

In [5]:
A = np.array([ [1, 2], [3, 4], [5, 6] ])

A

array([[1, 2],
       [3, 4],
       [5, 6]])

Interpretación:

* `A ∈ ℝ³ˣ²`
* representa una transformación lineal
  $$ T: \mathbb{R}^2 \rightarrow \mathbb{R}^3 $$


### 2.3 Tensores

Un tensor es una generalización multidimensional de vectores y matrices.

In [6]:
T = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

T.shape

(2, 2, 2)

Interpretación:

* tensor de orden 3
* estructura fundamental en física, IA y simulaciones

## 3. NumPy como implementación del álgebra lineal abstracta

NumPy no es una librería “numérica genérica”.
Es una **implementación computacional de los espacios vectoriales finito-dimensionales**.

Principio fundamental:

> Cada operación en NumPy corresponde a una operación algebraica bien definida,
> pero **no todas las operaciones algebraicas tienen el mismo símbolo**.

Esta distinción es crítica.

## 4. Multiplicación escalar

La multiplicación escalar consiste en multiplicar un vector o matriz por un número real.

In [7]:
v = np.array([1, 2, 3])
c = 3

c * v

array([3, 6, 9])

Resultado matemático:
$$
3 \cdot (1,2,3) = (3,6,9)
$$

Propiedad:

* preserva la dirección
* escala la magnitud

## 5. Producto elemento a elemento (NO es álgebra lineal)

En NumPy, el operador `*` entre arreglos **NO** representa el producto matricial.

In [9]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [10, 20],
    [30, 40]
])

A * B

array([[ 10,  40],
       [ 90, 160]])

Resultado:

$$
\begin{pmatrix}
1·10 & 2·20 \\
3·30 & 4·40
\end{pmatrix}
$$

Esto corresponde al **producto de Hadamard**, no al producto lineal clásico.

Error conceptual frecuente:

* asumir que `*` implementa composición de transformaciones
* produce resultados numéricamente válidos pero matemáticamente incorrectos


## 6. Producto matricial: composición de transformaciones

El producto matricial representa **composición de transformaciones lineales**.

En NumPy se expresa explícitamente con `@`.

In [10]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [2, 0],
    [1, 2]
])

A @ B

array([[ 4,  4],
       [10,  8]])

Interpretación matemática:
$$
(AB){ij} = \sum_k A{ik} B_{kj}
$$

Propiedades:

* no es conmutativo
* depende del orden
* preserva la estructura lineal


## 7. Producto matriz–vector

In [11]:
A = np.array([
    [1, 2],
    [3, 4]
])

v = np.array([1, 1])

A @ v

array([3, 7])

Interpretación:

* `v ∈ ℝ²`
* `A` actúa sobre `v`
* el resultado es un vector en ℝ²

Esto representa la aplicación de una transformación lineal a un estado.


## 8. Indexación: el origen de errores silenciosos

Python utiliza indexación basada en cero.

In [12]:
v = np.array([10, 20, 30])

v[0], v[1], v[2]

(np.int64(10), np.int64(20), np.int64(30))

Error conceptual común:

* confundir índices matemáticos (1-based) con índices computacionales (0-based)
* produce desplazamientos sistemáticos en algoritmos

## 9. Broadcasting: potencia y peligro

El broadcasting permite operar arreglos de distintas dimensiones bajo reglas implícitas.

In [13]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

v = np.array([10, 20, 30])

A + v

array([[11, 22, 33],
       [14, 25, 36]])

NumPy interpreta:

* `v` se replica por filas

Ventaja:

* eficiencia
* expresividad

Riesgo:

* operaciones matemáticamente inválidas pueden ejecutarse sin error

## 10. Errores conceptuales más frecuentes

1. Confundir `*` con producto matricial
2. Ignorar dimensiones antes de multiplicar
3. Asumir conmutatividad
4. No distinguir entre vector fila y columna
5. Confiar en resultados numéricos sin interpretación algebraica

## 11. Principio estructural

La computación no simplifica el álgebra lineal:
la **expone**.

Cada arreglo representa un objeto matemático.
Cada operación representa una ley estructural.

Dominar álgebra lineal con Python implica:

* pensar en términos de espacios,
* operar con conciencia de dimensiones,
* interpretar cada resultado como una transformación del espacio.

Este documento establece el punto de partida formal para todo el desarrollo posterior:
sin esta base, cualquier aplicación en física, inteligencia artificial o simulación es conceptualmente frágil.