# Operaciones con Matrices

## Estructura Algebraica, Determinantes y Fundamentos Computacionales

## Resumen

Se desarrolla una formulación rigurosa de la teoría matricial dentro del álgebra lineal, incluyendo vectores, matrices, operaciones fundamentales, matriz identidad, potencias, matrices booleanas, producto booleano, matriz transpuesta, matriz inversa y determinante. Se incorporan formalizaciones algebraicas, interpretación estructural y validación computacional.


# 1. Estructura Formal de Vectores y Matrices

Sea $ \mathbb{F} $ un cuerpo (usualmente $ \mathbb{R} $ o $ \mathbb{C} $).

## 1.1 Vector

Un vector fila:

$$
u = (a_1, a_2, \dots, a_n) \in \mathbb{F}^n
$$

Un vector columna:

$$
v =
\begin{pmatrix}
a_1 \\
a_2 \\
\vdots \\
a_n
\end{pmatrix}
$$

El vector cero satisface:

$$
\mathbf{0} = (0,0,\dots,0)
$$

### Implementación

In [1]:
import numpy as np

u = np.array([1, 3, -5, 8])
v = np.zeros(4)

u, v

(array([ 1,  3, -5,  8]), array([0., 0., 0., 0.]))

# 2. Definición General de Matriz

Una matriz $ A \in \mathbb{F}^{m \times n} $:

$$
A = [a_{ij}]
$$

donde:

* $ i = 1,\dots,m $
* $ j = 1,\dots,n $

### Ejemplo

In [2]:
A = np.array([[1,2,3],
              [4,5,6]])

A.shape

(2, 3)

# 3. Operaciones Fundamentales

## 3.1 Suma

$$
(A+B)*{ij} = a*{ij} + b_{ij}
$$

In [3]:
B = np.array([[6,5,4],
              [3,2,1]])

A + B

array([[7, 7, 7],
       [7, 7, 7]])

## 3.2 Producto por Escalar

$$
(kA){ij} = k a{ij}
$$

In [4]:
3 * A

array([[ 3,  6,  9],
       [12, 15, 18]])

## 3.3 Producto Matricial

Sea:

* $ A \in \mathbb{F}^{m \times p} $
* $ B \in \mathbb{F}^{p \times n} $

$$
C = AB, \quad c_{ij} = \sum_{k=1}^{p} a_{ik} b_{kj}
$$

In [ ]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

A @ B

### Propiedades Algebraicas

* Asociatividad: $ (AB)C = A(BC) $
* Distributividad
* No conmutatividad en general

# 4. Matriz Identidad

Definida mediante delta de Kronecker:

$$
I_n = [\delta_{ij}]
$$

donde:

$$
\delta_{ij} =
\begin{cases}
1 & i=j \\
0 & i\ne j
\end{cases}
$$

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Propiedad fundamental:

$$
AI = IA = A
$$

# 5. Potencia de una Matriz

Para $ A \in \mathbb{F}^{n\times n} $:

$$
A^2 = AA, \quad A^{k+1} = A^k A
$$

In [6]:
A = np.array([[2,1],
              [1,2]])

np.linalg.matrix_power(A, 3)

array([[14, 13],
       [13, 14]])

# 6. Matrices Booleanas

Sea $ A \in {0,1}^{m \times n} $.

## 6.1 Unión

$$
(A \vee B)*{ij} = a*{ij} \lor b_{ij}
$$

## 6.2 Intersección

$$
(A \wedge B)*{ij} = a*{ij} \land b_{ij}
$$

In [7]:
A = np.array([[1,0,1],
              [0,1,0]])

B = np.array([[1,1,0],
              [0,1,1]])

union = np.logical_or(A, B).astype(int)
inter = np.logical_and(A, B).astype(int)

union, inter

(array([[1, 1, 1],
        [0, 1, 1]]),
 array([[1, 0, 0],
        [0, 1, 0]]))

## 6.3 Producto Booleano

$$
c_{ij} = \bigvee_{k} (a_{ik} \land b_{kj})
$$

In [8]:
def producto_booleano(A, B):
    m, p = A.shape
    p, n = B.shape
    C = np.zeros((m,n), dtype=int)
    for i in range(m):
        for j in range(n):
            C[i,j] = int(any(A[i,k] and B[k,j] for k in range(p)))
    return C

producto_booleano(A, B.T)

array([[1, 1],
       [1, 1]])

# 7. Matriz Transpuesta

$$
A^T_{ij} = A_{ji}
$$

In [9]:
A = np.array([[1,2,3],
              [4,5,6]])

A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# 8. Matriz Inversa

Una matriz $ A $ es invertible si:

$$
\exists A^{-1} \text{ tal que } AA^{-1} = I
$$

In [10]:
A = np.array([[2,5],
              [1,3]])

np.linalg.inv(A)

array([[ 3., -5.],
       [-1.,  2.]])

Verificación:

In [11]:
A @ np.linalg.inv(A)

array([[1., 0.],
       [0., 1.]])

# 9. Determinante

## 9.1 Orden 2

$$
\det(A) = ad - bc
$$

In [12]:
A = np.array([[a:=2, b:=3],
              [c:=4, d:=5]])

np.linalg.det(A)

np.float64(-2.0)

## 9.2 Regla de Sarrus (3×3)

Para:

$$
A =
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{pmatrix}
$$

$$
\begin{aligned}
\det(A) = \quad & a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32}\
- a_{13}a_{22}a_{31} - a_{11}a_{23}a_{32} - a_{12}a_{21}a_{33}
\end{aligned}
$$

In [13]:
A = np.array([[3,2,1],
              [-1,-2,0],
              [0,2,1]])

np.linalg.det(A)

np.float64(-6.0)

## 9.3 Definición General

$$
\det(A) =
\sum_{\sigma \in S_n}
\text{sgn}(\sigma)
\prod_{i=1}^{n}
a_{i,\sigma(i)}
$$

Implementación simbólica:

In [14]:
import sympy as sp

A = sp.Matrix([[3,2,1],
               [-1,-2,0],
               [0,2,1]])

A.det()

-6

# 10. Relación con Sistemas Lineales

Un sistema:

$$
AX = B
$$

donde:

* $ A $ es matriz de coeficientes
* $ X $ vector incógnitas
* $ B $ vector términos independientes

Resolución computacional:

In [15]:
A = np.array([[2,1],
              [5,3]])

B = np.array([1,4])

np.linalg.solve(A,B)

array([-1.,  3.])

# Conclusión

La teoría matricial constituye una extensión estructural del álgebra lineal que permite modelar transformaciones lineales, resolver sistemas de ecuaciones, estudiar estabilidad estructural mediante determinantes y formalizar procesos booleanos aplicables en grafos y teoría de redes.

El determinante caracteriza invertibilidad, la matriz identidad estructura el grupo multiplicativo general $ GL(n,\mathbb{F}) $, y las potencias matriciales permiten estudiar dinámica discreta, diagonalización y espectros propios.

La integración formal con implementación computacional garantiza reproducibilidad algebraica, verificación simbólica y experimentación numérica, consolidando un marco matemático coherente para desarrollos posteriores en análisis espectral, mecánica cuántica, teoría de control y criptografía algebraica.
